class Settlement
  attr_reader :name, :description, :shops, :board

  def initialize(plot)
    @name        = set_name()
    @description = set_description()
    @shops       = set_shops()
    @board       = set_board(plot)
  end

  private

  def set_name()
    # Total 74 Prefixes
    prefix = ["Angel", "Autumn", "Basin", "Black", "Brine", "Bronze", "Cave", "Clay", "Cloud", "Cold", "Crag", "Crow", "Crystal", "Curse", "Dead", "Dire", "Dirt", "Dry", "Dusk", "Edge", "Elder", "Ever", "Fall", "Far", "Flat", "Gloom", "Gold", "Grass", "Green", "Hazel", "Hound", "Iron", "Knight", "Lake", "Light", "Lost", "Mad", "Mage", "Maple", "Mid", "Mill", "Mist", "Moon", "Mud", "Mute", "Never", "Ocean", "Pearl", "Pine", "Pond", "Raven", "Rock", "Rogue", "Rose", "Shade", "Silent", "Sleek", "Sly", "Small", "Snow", "South", "Stag", "Star", "Steam", "Steel", "Steep", "Stone", "Summer", "Swamp", "Thorn", "Timber", "Trade", "West", "Wind"]
    # Total 70 adjes
    adj = ["band", "barrow", "bay", "bell", "borough", "brook", "burgh", "burn", "cairn", "call", "chill", "cliff", "crest", "dale", "denn", "drift", "fell", "ford", "forest", "fort", "front", "frost", "garde", "glen", "grave", "guard", "gulch", "hallow", "ham", "haven", "helm", "hill", "hold", "holde", "keep", "land", "light", "maw", "mere", "minster", "mire", "mond", "moor", "mount", "mouth", "pass", "pond", "post", "rest", "shade", "shield", "shire", "shore", "spell", "stall", "star", "summit", "valley", "vault", "vein", "view", "ville", "wall", "wallow", "ward", "water", "well", "wharf", "wind", "wood"]
    return "#{prefix[rand(74)]}#{adj[rand(70)]}"
  end # set_name()

  def set_description()
    return "You enter the village and are greeted by its #{["wooden", "stone", "brick"][rand(3)]} buildings."
  end #set_description()

  def set_store_name(type)
    names = {
      "general" => {
        prefix: [],
        adj: ["A New View", "About Time", "Age of Vintage", "Aged Goodness", "Anecdotes", "Another Man's Treasures", "Another's Treasures", "Antique Cache", "Antique Cuties", "Antique Hut", "Antique Trove", "Antiquities", "Authentic Antiquities", "Beautiful Salvage", "Blasts from the Past", "Bygones", "Checkered Pasts", "Cozy Collectibles", "Dinky and Dainty", "Discoveries", "Drab to Fab", "Echoes of the Past", "Established Goods", "Focus of the Past", "Focus on the Past", "Forget Me Nots", "Forgotten Furnishings", "From Oblivion", "From Time Immemorial", "Frozen in Time", "General Goods", "Good As New", "Good Ol' Days", "Hodge Podge Lodge", "Honest Heirlooms", "In-Of-Date", "Joys For Forever", "Junk Deluxe", "Knick-knack Paddywhack Shack", "Little Collectibles", "Living Memories", "Long Time No See", "Lost and Found in Time", "Matters of Time", "Memory Lane", "Miracles of the Past", "Mod Life", "Modern Memories", "Modern Vintage", "Odd Types", "Old and Bold", "Old Gold", "Old Roots", "Oldies and Goldies", "One Time or Another", "Out of the Attic", "Pandora's Box", "Paragon Prizes", "Pass On the Past", "Past Caring", "Past Meets Present", "Pockets of Time", "Precious Past", "Precious Things", "Presents for the Present", "Preserved", "Primes of the Past", "Rags and Riches", "Recent Memories", "Recollect Them All", "Recollectibles", "Reliquary", "Remains to be Seen", "Remember", "Renewed Life", "Renewed Memories", "Retro Relics", "Revered Relics", "Revival", "Salvage Garden", "Secrets of the Past", "Shared Memories", "Stuff and Things", "Sweet Memories", "Tales of the Past", "Tales Resold", "Tales Retold", "The Antique Market", "The Salvage Beast", "The Time is Ripe", "The Treasure Trove", "Things Past", "Thingymabobs", "Time Honored", "Time Not Forgotten", "Time Recovered", "Timeless Treasures", "Timeless Trinkets", "Times Remembered", "Twosided", "Utter Clutter", "Vestiges of the Past", "Vintage", "Vintage Baby", "Warm Wares", "Wayward Wealths", "Well of a Time", "Whispers of the Past", "Wonders of the Past"],
        suffix: []
      },
      "magic" => {
        prefix: ["The Adorable", "The Amusing", "The Angry", "The Arcane", "The Awesome", "The Awkward", "The Baby", "The Banished", "The Bathing", "The Bigger", "The Bitter", "The Bleeding", "The Blind", "The Blissful", "The Bound", "The Bright", "The Brilliant", "The Broken", "The Champion's", "The Clean", "The Clever", "The Cone", "The Dancing", "The Dark", "The Dizzy", "The Dragon", "The Ebon", "The Fancy", "The Fantastic", "The Fel", "The Gentle", "The Glass", "The Glowing", "The Golden", "The Green", "The Grumpy", "The Heavy", "The Invisible", "The Last", "The Living", "The Lucky", "The Minotaur", "The Ninth", "The Old", "The Pestle", "The Philosopher's", "The Phony", "The Plain", "The Quiet", "The Raven's", "The Ring", "The Serene", "The Silver", "The Small", "The Sneaky", "The Steel", "The Storm", "The Summoned", "The Third", "The Thunder", "The Tinkered", "The Triton's", "The Twinkle", "The Unicorn's", "The Wand's", "The Wicked"],
        adj: ["Artifact", "Aspect", "Banshee", "Beacon", "Beast", "Bigfoot", "Blizzard", "Book", "Boots", "Bunyip", "Centaur", "Chupacabra", "Cockatrice", "Cupid", "Cyclops", "Dryad", "Elemental", "Elf", "Feathered Serpent", "Focus", "Gargoyle", "Goods", "Harpy", "Hippocampus", "Hippogriff", "Hobgoblin", "Horn", "Hourglass", "Human", "Hydra", "Imp", "Infinity", "Lead", "Life", "Manticore", "Marker", "Maze", "Message", "Nymph", "of Cold", "of Life", "Ogre", "Pegasus", "Quill", "Ring", "Robe", "Rune", "Sasquatch", "Scroll", "Seal", "Shapeshifter", "Siren", "Skull", "Spell", "Sphere", "Star", "Statue", "Steed", "Stone", "Tiara", "Tome", "Trident", "Troll", "Unicorn", "Vampire", "Vial", "Want", "Werewolf", "Wish", "World Turtle", "Wraith"],
        suffix: []
      },
      "tavern" => {
        prefix: ["The Abstract", "The Adorable", "The Anxious", "The Armed", "The Asian", "The Australian", "The Awesome", "The Awful", "The Beautiful", "The Bitter", "The Bloody", "The Blushing", "The Bored", "The Cheap", "The Closed", "The Cunning", "The Daily", "The Dapper", "The Defiant", "The Deserted", "The Devilish", "The Dirty", "The Dry", "The Dwarvish", "The Educated", "The Entertaining", "The Even", "The Faint", "The First", "The Frozen", "The Full", "The Fuzzy", "The Gigantic", "The Glistening", "The Gray", "The Grumpy", "The Happy", "The Hissing", "The Hollow", "The Hot", "The Hypnotic", "The Interesting", "The International", "The Jewish", "The Kaput", "The Known", "The Lazy", "The Lethal", "The Limping", "The Long", "The Massive", "The Mean", "The Metal", "The Middle", "The Misty", "The Mixed", "The Naive", "The Narrow", "The Nasty", "The National", "The Natural", "The Obedient", "The Oceanic", "The Pathetic", "The Psychotic", "The Puny", "The Puzzling", "The Rabid", "The Rapid", "The Relieved", "The Right", "The Round", "The Royal", "The Scared", "The Scattered", "The Shaggy", "The Shaking", "The Short", "The Shouting", "The Sick", "The Sleeping", "The Snobbish", "The Soft", "The Square", "The Steel", "The Superb", "The Supreme", "The Tasty", "The Terrible", "The Thin", "The Thundering", "The Tired", "The Triangular", "The Ugliest", "The Unusual", "The Venomous", "The Violent", "The Voiceless", "The Waiting", "The Well-Groomed", "The Wicked", "The Windy", "The Wretched", "The Wrong", "Ye Olde"],
        adj: ["Accordion", "Ant", "Anteater", "Ape", "Apple", "Bamboo", "Bass", "Beaver", "Birds", "Bone", "Bongo", "Book", "Branch", "Bunny", "Butterflies", "Chainmail", "Cherry", "Chicken", "Cloth", "Cookie", "Couple", "Crew", "Crocodile", "Crossbow", "Crow", "Crows", "Cushion", "Dark Elf", "Doves", "Dwarf", "Eagle", "Eel", "Elephant", "Fiddle", "Flame", "Flea", "Fly", "Gazelle", "Gentlewomen", "Giant", "Goat", "Gooseberry", "Gopher", "Gorilla", "Grotto", "Hag", "Hammer", "Hamsters", "Hill", "Hippo", "Horn", "Husband", "Ice", "Kangaroo", "Kiwi", "Knight", "Lamp", "Lavender", "Leg", "Lions", "Lobster", "Loch", "Lyre", "Mandolin", "Mango", "Meat", "Midget", "Mouse", "Nugget", "Nut", "Octopus", "Owl", "Pie", "Pike", "Pirate", "Plate", "Pony", "Queen", "Rhino", "Rhinoceros", "Rope", "Rose", "Salt", "Shipmate", "Skies", "Skull", "Snail", "Snakes", "Snowball", "Stars", "Steed", "Stone", "Swan", "Table", "Tankard", "Tigers", "Traveler", "Tree", "Triangle", "Trombone", "Tuba", "Tusk", "Willow", "Wood Elf", "Yew"],
        suffix: ["Pub", "Pub", "Pub", "Pub", "Tavern", "Tavern", "Tavern", "Tavern", "Inn", "Inn", "Inn", "Bar", "Bar", "Bar", "", "", "", "", "", ""]
      },
      "temple" => {
        prefix: ["Altar Of", "Cathedral Of", "Chapel Of", "Church Of", "House Of", "Monastery Of", "Mosque Of", "Pagoda Of", "Pantheon Of", "Sanctuary Of", "Sanctum Of", "Shrine Of", "Synagogue Of", "Temple Of"],
        adj: ["Aglios", "Agony", "Allegiance", "Altar Of Altar Of Edos", "Altar Of Sanctum Of Fate", "Amnesia", "Ania", "Babum", "Bliss", "Bupeyar", "Chaos", "Chapel Of Insight", "Church Of Knowledge", "Church Of Purpose", "Clairvoyance", "Confidence", "Cyfdum", "Decay", "Dedication", "Defdar", "Dunia", "Duteus", "Earus", "Emdum", "Enir", "Epemis", "Eruer", "Esjun", "Eternity", "Exile", "Felicity", "Fycmjir", "Gasarus", "Gizaldir", "Grief", "Horeus", "Humility", "Integrity", "Kinship", "Kyfmus", "Lament", "Life", "Logthar", "Lore", "Mosque Of Dreams", "Nubum", "Odite", "Ogros", "Onos", "Order", "Orysus", "Owthar", "Pantheon Of Quests", "Probabilities", "Purpose", "Pursuit", "Qaktarr", "Qirione", "Repose", "Resolutions", "Reverence", "Revival", "Rytyx", "Sanctum Of Ania", "Sanctum Of Fire", "Seclusion", "Secrets", "Shrine Of House Of Water", "Silence", "Spirits", "Temple Of Determination", "Temple Of Dozagi", "Temple Of Loss", "Termination", "Thirst", "Time", "Tragedy", "Tranquility", "Triumph", "Twilight", "Tydros", "Ukdros", "Unborh", "Utjun", "Utopia", "Uzius", "Visions", "Vuhorr", "Wisdom", "Withdrawal", "Xetos", "Xewlo", "Xidon", "Yagi", "Ymnus", "Ynaldir", "Ynysus", "Ypteus", "Yqmus", "Yzdarr", "Yzrus", "Zeal", "Zilarus"],
        suffix: []
      },
      "weapons" => {
        prefix: [],
        adj: ["A Steel", "Adore Ore", "Anvil Crafts", "Anvil Mastery", "Anvil Works", "Anything Metal", "Ball of Fire", "Balls of Fire", "Baptisms of Fire", "Bars of Steel", "Beat the Heat", "Beats of Fire", "Belly Fires", "Between Hammer and Anvil", "Blackstone Forge", "Blazing Blacksmiths", "Blazing Glory", "Blazing Trails", "Blue Blazes", "Blue Steel", "Breathing Fire", "By Hammer and Hand", "Clamorize", "Clobbering Time", "Curious Forge", "Fire & Brimstone", "Fire It Up", "Flux Crux", "Flux Deluxe", "Forge and Fabricate", "Forge away", "Forging Ahead", "Forging Matters", "George's Forge", "Gorge 'n Forge", "Hammer Clamor", "Hammer Glamor", "Hammer Home", "Hammer It Hot", "Hammer Out", "Hammer Time", "He Who Smelt It", "Heat Up", "Heavy Metal Works", "Heavy Metals", "Hot diggety dog", "Hot diggety", "Hot Hot Hot", "Hot Iron", "Hot Rod", "Hot Spot", "Hot Stuff", "Hot-Shot", "Ingot This", "Iron Designs", "Iron Man", "Iron Woman", "Ironclad", "Matter of Metal", "Metal Accent", "Metal Arts", "Metal Expertise", "Metal Fabrications", "Metal Mania", "Metal Maniac", "Metal Mastery", "Metal Trades", "Metallurgy", "Metalworks of Art", "Mind Over Metal", "Mineral Minded", "Mr Smith", "Mrs Smith", "Nice Ring To It", "Ore Decor", "Ore Galore", "Ore Really", "Ore Restore", "Ore Store", "Phoenix Fire", "Pound World", "Real Steel", "Smelt Art", "Smelt in my Arms", "Smelt My Hearth", "Smelting Pot", "Smelts of Heaven", "Smite Thee", "Smith Thee", "Smithen", "Smitten", "Sparks and Flames", "Squeal of Steel", "Steel Arms", "Steel Fabrications", "Steel Ideal", "Steel Thunder", "Steel Wings", "Stop Hammer Time", "Sword in the Forge", "Sword in the Stone", "The Ancient Anvil", "The Blacksmith's Forge", "The Clamor Shop", "The Clank Tank", "The Fire Squire", "The Gorge Forge", "The Hot Forge", "The Hot Ticket", "The Metal Petal", "The Right Clank", "The Smelt Belt", "The Smelt Celt", "The Smithy", "The Unbreakable Anvil", "There Be Smoke", "True as Steel", "Under Construction", "While the Iron's Hot", "Young Flames"],
        suffix: []
      }
    }
  end # set_store_name()
end
